### ISSUE TITLE
Http tutorial skips over essential steps

### ISSUE THREAD

**Issue by Kilian** [evancz/guide.elm-lang.org#24] opened 2016-07-17 11:20 UTC
The tutorial on https://github.com/evancz/guide.elm-lang.org/blob/master/architecture/effects/http.md is not self-contained  and tripped me up for a number of reasons.
- does not mention you need to add Import Http, for that you need to look at the online example
- it is not explained you need to _install_ the http module first
- the name to use for the http module is not self-evident for people looking at the tutorial. I tried elm-lang/http, elm-http and http before asking in Slack. I suppose other users would just abandon the guide. The previous page introduces new imports but they do not require additional installs.

"evancz/elm-http" is not a logical name and it, alongside how to install it, should be mentioned in the tutorial.

A quick mention on top of phase two of "by the way, the http module is located here, and you need to install and import it"  would be a good idea so people do not have to look elsewhere to get their local example working.

**Comment by TheZoq2** [comment] 2016-08-20 10:00
I ran into the same issue, both with HTTP and Json

**Comment by eliecerthoms** [comment] 2016-09-26 03:11
Yeah, this guide needs a revamp, it should be more like MDN where you can contribute and even translate... Next big step... Wish I knew enough to start moving it myself

**Comment by adsteel** [comment] 2017-03-09 18:14
I was able to fill in the missing steps by first installing the elm-lang/http package

```sh
$ elm-package install elm-lang/http
```

And then by adding these imports at the top of the file:
```elm
import Http exposing (..)
import Json.Decode as Json exposing (..)
```

**Comment by adsteel** [comment] 2017-03-09 18:16
This is also a duplicate of this issue: https://github.com/evancz/guide.elm-lang.org/issues/21

**Comment by evancz** [comment] 2018-08-21 20:15
The new version of the book includes all the examples in full!

**Closed by evancz** 2018-08-21 20:15 UTC
